<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>VDTraceAutoStartPlugin</AssemblyName>
    <RootNamespace>VDTraceAutoStartPlugin</RootNamespace>
    <LangVersion>latest</LangVersion>
    <OutputPath>..\..\bin\release\bepinex_plugin\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx.Core">
      <HintPath>F:\Program Files\Endfield Game\BepInEx\core\BepInEx.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx.Unity.IL2CPP">
      <HintPath>F:\Program Files\Endfield Game\BepInEx\core\BepInEx.Unity.IL2CPP.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
